Us 0002 view job role info
jackpollinsK/team_4_Backend pull request #10
Opened 2024-07-30 09:27 UTC by jackpollinsK

2024-07-30 10:47 UTC, ThomasS-kainos approved these changes, later dismissed

2024-07-31 10:43 UTC, shaunganley requested changes

2024-07-31 10:43 UTC, shaunganley commented on src/main/java/org/example/controllers/JobRoleController.java
> +            return Response.ok().entity(jobRoles).build();
why make this change?

2024-07-31 10:43 UTC, shaunganley commented on src/main/java/org/example/controllers/JobRoleController.java
> +            }
this logic should be in the service and throw an exception if null

2024-07-31 10:43 UTC, shaunganley commented on src/main/resources/db/migration/V6__create_job_roles_table.sql
> +    job_spec VARCHAR(500) NOT NULL,
don't update existing migrations as they've already been run. instead add a new migration to alter the table to add new columns

2024-07-31 15:52 UTC, Egal97 approved these changes

2024-08-01 10:24 UTC, shaunganley approved these changes

2024-08-01 10:44 UTC, merged