Us050 apply for role
jackpollinsK/team_4_Backend pull request #18
Opened 2024-08-08 13:15 UTC by PhilipGardinerK

Added the "in progress" functionality

2024-08-08 13:50 UTC, ThomasS-kainos approved these changes

2024-08-08 14:07 UTC, shaunganley requested changes
not needed. we can set the status of the application to in progress on the apply endpoint

2024-08-08 14:07 UTC, shaunganley commented on src/main/java/org/example/controllers/ApplicationController.java
> +    @POST
should this be a get?

2024-08-08 15:06 UTC, Egal97 approved these changes

2024-08-09 07:07 UTC, shaunganley approved these changes

2024-08-09 07:24 UTC, merged